Clab\ShopBundle\Entity\CartElement:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        api_name:
            expose: true
            read_only: true
            accessor:
                getter: getApiName
            groups: [app,public,pro]
        api_type:
            expose: true
            read_only: true
            accessor:
                getter: getApiType
            groups: [app,public,pro]
        quantity:
            expose: true
            read_only: true
            groups: [app,public,pro]
        price:
            expose: true
            read_only: true
            groups: [app,public,pro]
        product:
            expose: true
            groups: [app,public,pro]
        hash:
            expose: true
            read_only: true
            groups: [app,public,pro]
        childrens:
            expose: true
            read_only: true
            groups: [app,public,pro]
        choices:
            expose: true
            read_only: true
            groups: [app,public,pro]
        meal:
            expose: true
            read_only: true
            groups: [app,public,pro]
        parent:
            expose: true
            read_only: true
            groups: [app,public,pro]
