Clab\ShopBundle\Entity\Coupon:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
        name:
            expose: true
            read_only: true
        amount:
            expose: true
            read_only: true
        percent:
            expose: true
            read_only: true
        maxForPercent:
            expose: true
            read_only: true
        verbose:
            expose: true
            read_only: true
            accessor:
                getter: verbose
        managerVerbose:
            expose: true
            read_only: true
            accessor:
                getter: getManagerVerbose
