Clab\ShopBundle\Entity\OrderDetail:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        orderType:
            expose: true
            read_only: true
            accessor:
                getter: getOrderType
            groups: [app,public,pro,follow]
        hash:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        state:
            expose: true
            read_only: true
            accessor:
                getter: getState
            groups: [app,public,pro,follow]
        created:
            expose: true
            read_only: true
            accessor:
                getter: getCreated
            groups: [app,public,pro,follow]
        isPaid:
            expose: true
            read_only: true
            accessor:
                getter: getIsPaid
            groups: [app,public,pro,follow]
        restaurant:
            expose: true
            read_only: true
            accessor:
                getter: getRestaurant
            groups: [app,follow]
        source:
            expose: true
            read_only: true
            accessor:
                getter: getSource
            groups: [app,public,pro,follow]
        price:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        currentPrice:
            expose: true
            read_only: true
            accessor:
                getter: getPrice
            groups: [app,public,pro,follow]
        onlinePayment:
            expose: true
            read_only: true
            accessor:
                getter: getOnlinePayment
            groups: [app,public,pro,follow]
        day:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        time:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        schedule:
            expose: true
            read_only: true
            accessor:
                getter: getApiSchedule
            type: string
            groups: [app]
        comment:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        restaurantDiscountPrice:
            expose: true
            read_only: true
            accessor:
                getter: getRestaurantDiscountPrice
            groups: [app]
        restaurantCouponPrice:
            expose: true
            read_only: true
            accessor:
                getter: getRestaurantCouponPrice
            groups: [app]
        clickeatCouponPrice:
            expose: true
            read_only: true
            accessor:
                getter: getClickeatCouponPrice
            groups: [app]
        taxesAmount:
            expose: true
            read_only: true
            accessor:
                getter: getTaxesAmount
            groups: [app,public,pro,follow]
        directPayment:
            expose: true
            read_only: true
            accessor:
                getter: directPaymentEnabled
            groups: [app,public,pro,follow]
        cart:
            expose: true
            read_only: true
            until_version: 2.9
            groups: [app,public,pro]
        profile:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        delivery:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        tva55:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        tva7:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        tva10:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        tva20:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        onSitePayments:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        preparationState:
            expose: true
            read_only: true
            accessor:
                getter: getPreparationState
            groups: [app,public,pro,follow]
        covers:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
