Clab\ShopBundle\Entity\Cart:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        elements:
            expose: true
            read_only: true
            groups: [app,public,pro]
        coupon:
            expose: true
            read_only: true
            groups: [app,public,pro]
        discount:
            expose: true
            read_only: true
            groups: [app,public,pro]
        discountAmount:
            expose: true
            read_only: true
            groups: [app,public,pro]
        discountPrice:
            expose: true
            read_only: true
            groups: [app,public,pro]
        couponAmount:
            expose: true
            read_only: true
            groups: [app,public,pro]
        totalPrice:
            expose: true
            read_only: true
            groups: [app,public,pro]
        totalProducts:
            expose: true
            read_only: true
            groups: [app,public,pro]
        woodSticks:
            expose: true
            read_only: true
            groups: [app,public,pro]
        loyalties:
            expose: true
            read_only: true
            groups: [app,public,pro]
