Clab\ShopBundle\Entity\Sale:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
        value:
            expose: true
            read_only: true
