Clab\ShopBundle\Entity\Discount:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,pro]
        created:
            expose: true
            groups: [app,pro]
        percent:
            expose: true
            groups: [app,search,public,pro,favorite]
        type:
            expose: true
            groups: [app,search,public,pro,favorite]
        description:
            expose: true
            accessor:
                getter: getDescription
            groups: [app,search,public,pro,favorite]
        isOnline:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
            groups: [app,pro]
        name:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
