Clab\RestaurantBundle\Entity\Product:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        created:
            expose: true
            groups: [app,pro]
        isOnline:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
            groups: [app,pro]
        isOnlineCaisse:
            expose: true
            read_only: true
            groups: [app,pro]
        name:
            expose: true
            accessor:
                getter: getName
                setter: setName
            groups: [app,search,public,pro]
        slug:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        description:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        is_online:
            expose: true
            read_only: true
            accessor:
                getter: getIsOnline
            groups: [app,pro]
        price:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        currentPrice:
            expose: true
            read_only: true
            accessor:
                getter: _getCurrentPrice
            groups: [app,search,public,pro]
        deliveryPrice:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        priceOnSite:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        managerPrice:
            expose: true
            read_only: true
            accessor:
                getter: getPrice
            groups: [app,pro]
        hasOption:
            expose: true
            read_only: true
            accessor:
                getter: hasOption
            groups: [app,search,public,pro]
        category:
            expose: true
            read_only: true
            groups: [app,search,pro]
        tax:
            expose: true
            read_only: true
            groups: [app,pro]
        taxDelivery:
            expose: true
            read_only: true
            groups: [app,pro]
        taxOnSite:
            expose: true
            read_only: true
            groups: [app,pro]
        options:
            expose: true
            read_only: true
            groups: [app,search,public,pro,extended]
            accessor:
                getter: getOptions
        cover:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        coverSmall:
            expose: true
            read_only: true
            groups: [app,pro]
        coverFull:
            expose: true
            read_only: true
            groups: [app,pro]
        apiCover:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
            accessor:
                getter: getApiCover
        apiCoverEditable:
            expose: true
            read_only: true
            groups: [app,pro]
            accessor:
                getter: getApiCoverEditable
        stock:
            expose: true
            read_only: true
            groups: [app,pro]
        unlimitedStock:
            expose: true
            read_only: true
            groups: [pro]
            accessor:
                getter: getUnlimitedStock
        defaultStock:
            expose: true
            read_only: true
            groups: [pro]
            accessor:
                getter: getDefaultStock
        supplement:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        printers:
            expose: true
            read_only: true
            groups: [app, search, public, pro]

