Clab\RestaurantBundle\Entity\ProductOption:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        created:
            expose: true
            groups: [app,pro]
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
            groups: [app,pro]
        id:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        name:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        required:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        multiple:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        minimum:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        maximum:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        choices:
            expose: true
            read_only: true
            accessor:
                getter: getChoices
            groups: [app,search,public,pro]
        managerChoices:
            expose: true
            read_only: true
            groups: [app,pro]
            accessor:
                getter: getChoices
