Clab\RestaurantBundle\Entity\OptionChoice:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,public,pro]
        created:
            expose: true
            groups: [app,pro]
        isOnline:
            expose: true
            groups: [app,pro]
        value:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        option:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        price:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        currentPrice:
            expose: true
            read_only: true
            accessor:
                getter: getPrice
            groups: [app,search,public,pro]
        apiCover:
            expose: true
            read_only: true
            accessor:
                getter: getApiCover
            groups: [app,search,public,pro]
        cover:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        coverSmall:
            expose: true
            read_only: true
            groups: [app,pro]
        coverFull:
            expose: true
            read_only: true
            groups: [app,pro]
