Clab\RestaurantBundle\Entity\TimesheetValidation:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
        created:
            expose: true
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
        isPublished:
            expose: true
            read_only: true
