Clab\RestaurantBundle\Entity\StaffMember:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        created:
            expose: true
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
        name:
            expose: true
        description:
            expose: true
        apiCover:
            expose: true
            accessor:
                getter: getApiCover
