Clab\RestaurantBundle\Entity\Restaurant:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        created:
            expose: true
            groups: [app,pro]
        status:
            expose: true
            groups: [app,search,public,pro,favorite]
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
            groups: [app,pro]
        hasCaisse:
            expose: true
            accessor:
                getter: getHasCaisse
                setter: setHasCaisse
            groups: [app,pro]
        client:
            expose: true
            read_only: true
            accessor:
                getter: getClient
            groups: [app]
        flatTimeSheet:
            expose: true
            read_only: true
            accessor:
                getter: getFlatTimeSheet
            groups: [app,search,public,favorite]
        name:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite,follow]
        averagePrice:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        is_open:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        todayPlanning:
            expose: true
            read_only: true
            accessor:
                getter: getTodayPlanning
            groups: [app,search,public,pro]
        avgReviewScore:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        slug:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        isClickeat:
            expose: true
            read_only: true
            accessor:
                getter: getIsClickeat
            groups: [app,pro]
        isWhite:
            expose: true
            read_only: true
            accessor:
                getter: getIsWhite
            groups: [app,pro]
        isTtt:
            expose: true
            read_only: true
            accessor:
                getter: getIsTtt
            groups: [app,pro]
        isMobile:
            expose: true
            read_only: true
            accessor:
                getter: isMobile
            groups: [app,pro]
        description:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        phone:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        email:
            expose: true
            read_only: true
            groups: [app,pro]
        address:
            expose: true
            read_only: true
            accessor:
                getter: getAddress
            groups: [app,search,public,pro,favorite]
        slogan:
            expose: true
            read_only: true
            groups: [app,public,pro]
        cover:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        coverSmall:
            expose: true
            read_only: true
            groups: [app,pro]
        coverFull:
            expose: true
            read_only: true
            groups: [app,pro]
        coverBig:
            expose: true
            read_only: true
            groups: [app,pro]
        apiCover:
            expose: true
            read_only: true
            accessor:
                getter: getApiCover
            groups: [app,search,public,pro]
        distance:
            expose: true
            read_only: true
            groups: [app,search]
        discounts:
            expose: true
            read_only: true
            accessor:
                getter: getDiscounts
            groups: [app,pro]
        promotedProducts:
            expose: true
            read_only: true
            accessor:
                getter: getProducts
            groups: [app,public,pro]
        orderTypes:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        tags:
            expose: true
            read_only: true
            groups: [app,pro]
        extraTags:
            expose: true
            read_only: true
            groups: [app,pro]
        flatTags:
            expose: true
            accessor:
                getter: getFlatTags
            groups: [app,search,public,favorite]
        publicGallery:
            expose: true
            read_only: true
            groups: [app,public,pro]
        gallery:
            expose: true
            read_only: true
            groups: [app,public,pro]
        galleryMenu:
            expose: true
            read_only: true
            groups: [app,public,pro]
        socialProfile:
            expose : true
            read_only: true
            groups: [app,public,pro]
        activeDiscount:
            expose: true
            read_only: true
            groups: [app,search,public,favorite]
        isInFavorites:
            expose : true
            read_only: true
            groups: [app,public]
        website:
            expose : true
            read_only: true
            groups: [app,search,public,favorite]
        checkerBoardConfig:
            expose : true
            accessor:
                getter: getCheckerBoardConfig
            read_only: true
            groups: [app,pro,public]
        hasTicketRestoScan:
            expose : true
            accessor:
                getter: getHasTicketRestoScan
            read_only: true
            groups: [app,pro,public]
        caisseDiscountsLabels:
            expose : true
            accessor:
                getter: getCaisseDiscountsLabels
            read_only: true
            groups: [app,pro,public]
        caisseTags:
            expose : true
            accessor:
                getter: getCaisseTags
            read_only: true
            groups: [app,pro,public]
        printers:
            expose : true
            accessor:
                getter: getFormatedCaissePrinterLabels
            read_only: true
            groups: [app,pro,public]
        siret:
            expose: true
            accessor:
                getter: getSiret
            read_only: true
            groups: [app,search,public,pro,favorite]