Clab\RestaurantBundle\Entity\MealChoice:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
             groups: [app,search,public,pro]
        created:
            expose: true
             groups: [app,pro]
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
            groups: [app,pro]
        name:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        price:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
        product:
            expose: true
            read_only: true
            groups: [app,search,public,pro]
