Clab\ApiBundle\Entity\SessionCaisse:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            groups: [app,pro]
        created:
            expose: true
            groups: [app,pro]
        dateEnd:
            expose: true
            groups: [app,pro]
        dateStart:
            expose: true
            groups: [app,pro]
        formatedDateEnd:
            expose: true
            accessor:
                getter: getFormatedDateEnd
            groups: [app,pro]
        formatedDateStart:
            expose: true
            accessor:
                getter: getFormatedDateStart
            groups: [app,pro]
        cashFlowStart:
            expose: true
            groups: [app,pro]
        cashFlowEndTheoric:
            expose: true
            groups: [app,pro]
        cashFlowEnd:
            expose: true
            groups: [app,pro]
        cashFlowDiff:
            expose: true
            groups: [app,pro]
        refund:
            expose: true
            accessor:
                getter:
                    getRefund
            groups: [app,pro]
        cash:
            expose: true
            groups: [app,pro]
        cb:
            expose: true
            groups: [app,pro]
        restoTicket:
            expose: true
            groups: [app,pro]
        check:
            expose: true
            groups: [app,pro]
        amex:
            expose: true
            groups: [app,pro]
        productSwitch:
            expose: true
            groups: [app,pro]
        commercialGesture:
            expose: true
            groups: [app,pro]
        accidentalDebit:
            expose: true
            groups: [app,pro]
        testError:
            expose: true
            groups: [app,pro]
        clientProblem:
            expose: true
            groups: [app,pro]
        inOut:
            expose: true
            accessor:
                getter:
                    getInOut
            groups: [app,pro]
        inOuts:
            expose: true
            read_only: true
            accessor:
                getter:
                    getInOuts
            groups: [app]
        orders:
            expose: true
            accessor:
                getter:
                    getOrders
            groups: [app,pro]
        tva:
            expose: true
            accessor:
                getter:
                    getTva
            groups: [app,pro]
        commentary:
            expose: true
            groups: [app,pro]
        device:
            expose: true
            groups: [app,pro]
        device_name:
            expose: true
            groups: [app,pro]
