Clab\LocationBundle\Entity\Address:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,pro]
        name:
            expose: true
            read_only: true
            groups: [app,pro]
        street:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        zip:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        city:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        latitude:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        longitude:
            expose: true
            read_only: true
            groups: [app,search,public,pro,favorite]
        description:
            expose: true
            read_only: true
            accessor:
                  getter: fullStringDescription
            groups: [app,search,public,pro,favorite]
