Clab\LocationBundle\Entity\EventSchedule:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
        created:
            expose: true
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
        startTime:
            expose: true
            read_only: true
        endTime:
            expose: true
            read_only: true
        startDate:
            expose: true
            read_only: true
        endDate:
            expose: true
            read_only: true
