Clab\LocationBundle\Entity\Place:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
        created:
            expose: true
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
        name:
            expose: true
            read_only: true
        description:
            expose: true
            read_only: true
        address:
            expose: true
            read_only: true
        socialProfile:
            expose: true
            read_only: true
        coverPicturePath:
            expose: true
            read_only: true
            since_version: 3.0
        coverPicturePathSmall:
            expose: true
            read_only: true
            since_version: 3.0
        coverPicturePathFull:
            expose: true
            read_only: true
            since_version: 3.0
        profilePicturePath:
            expose: true
            read_only: true
            since_version: 3.0
        profilePicturePathSmall:
            expose: true
            read_only: true
            since_version: 3.0
        profilePicturePathFull:
            expose: true
            read_only: true
            since_version: 3.0
