# Byclickeat
multisite_get:
    path:  /
    defaults: { _controller: ClabMultisiteBundle:Multisite:get }

multisite_style:
    path:  /byclickeat/style.css
    defaults: { _controller: ClabMultisiteBundle:Multisite:style }

multisite_menu:
    path:  /menu
    defaults: { _controller: ClabMultisiteBundle:Multisite:menu }

multisite_planning:
    path:  /itineraire
    defaults: { _controller: ClabMultisiteBundle:Multisite:planning }

multisite_gallery:
    path:  /photos
    defaults: { _controller: ClabMultisiteBundle:Multisite:gallery }

multisite_social:
    path:  /actualités
    defaults: { _controller: ClabMultisiteBundle:Multisite:social }

multisite_menu_product:
    path:  /menu/product/{slug}
    defaults: { _controller: ClabMultisiteBundle:Multisite:product }

multisite_reviews:
    path:  /les-avis
    defaults: { _controller: ClabMultisiteBundle:Multisite:reviews }

multisite_reviews_write:
    path:  /nouvel-avis
    defaults: { _controller: ClabMultisiteBundle:Multisite:writeReview }

multisite_contact:
    path:  /contact
    defaults: { _controller: ClabMultisiteBundle:Multisite:contact }

multisite_sitemap:
    path:  /sitemap.{_format}
    defaults: { _controller: ClabMultisiteBundle:Multisite:sitemap, _format: xml }
    requirements: { _format: xml, _method: GET }
