<?php

namespace Clab\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientConfigurationRepository extends EntityRepository
{
}
