<?php

namespace Clab\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function findAllowedForUser($user)
    {
	$restaurantRepository = $this->getEntityManager()->getRepository('ClabBoardBundle:Client');

	$qb = $restaurantRepository->createQueryBuilder('c');

	$qb->innerJoin('c.managers', 'm', 'WITH', 'm.id = :managerId')
	    ->setParameter('managerId', $user->getId());

	$query = $qb->getQuery();
	$results = $query->getResult();

	return $results;
    }
}
