Clab\DeliveryBundle\Entity\Delivery:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        created:
            expose: true
            groups: [app,public,pro,follow]
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
            groups: [app,public,pro,follow]
        state:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        start:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        end:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        deliveryTime:
            expose: true
            read_only: true
            accessors:
                getter: deliveryTime
            groups: [app,public,pro,follow]
        latitude:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        longitude:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        code:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        skipCode:
            expose: true
            read_only: true
            accessors:
                getter: getSkipCode
            groups: [app,public,pro,follow]
        codeCustomer:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        comment:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        customer:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
            accessors:
                getter: getCustomer
        customerGrade:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        customerComment:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        address:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        pickupAddress:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        trackingId:
            expose: true
            read_only: true
            accessors:
                getter: getTrackingId
            groups: [app,public,pro,follow]
        deliveryMan:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]
        order:
            expose: true
            read_only: true
            groups: [app,public,pro,follow]