Clab\DeliveryBundle\Entity\DeliverySchedule:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
        created:
            expose: true
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
        name:
            expose: true
            read_only: true
            groups: [pro]
        slotLength:
            expose: true
            read_only: true
            groups: [pro]