Clab\MediaBundle\Entity\Gallery:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        created:
            expose: true
            groups: [app,pro]
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
            groups: [app,pro]
        mobileCover:
            expose: true
            read_only: true
            accessor:
                getter: getCover
            groups: [app,search,public,pro]
        cover:
            expose: true
            read_only: true
            accessor:
                getter: getCover
            groups: [app,search,public,pro]
        images:
            expose: true
            groups: [app,public,pro]
