<?php

namespace Clab\BoardBundle\Repository;

/**
 * AdditionalSaleRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditionalSaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneAvailable(array $parameters = array())
    {
        $qb = $this->createQueryBuilder('additionalSale')
            ->where('additionalSale.isOnline = 1')
        ;

        foreach ($parameters as $key => $param) {
            $qb->andWhere('additionalSale.'.$key.' = :'.$key)
                ->setParameter($key, $param);
        }

        return $qb->getQuery()->getOneOrNullResult();
    }
}
