<?php

namespace Clab\BoardBundle\Repository;

use Clab\BoardBundle\Entity\Company;

/**
 * UserDataBaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
}
