<?php

namespace Clab\BoardBundle\Repository;

use Clab\BoardBundle\Entity\Client;
use Clab\RestaurantBundle\Entity\Restaurant;

/**
 * UserDataBaseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDataBaseRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForChainStore(Client $client)
    {
        $qb = $this->createQueryBuilder('udb')
            ->leftJoin('udb.restaurant','r')
            ->where('r.client = :client')
            ->setParameter('client',$client)
        ;

        return $qb->getQuery()->getResult();
    }

    public function findAllFiltered(Restaurant $restaurant, $search = null)
    {
        $qb = $this->createQueryBuilder('u')
            ->leftJoin('u.restaurant', 'r')
            ->where('r = :restaurant')
            ->andWhere('u.isDeleted = false')
            ->setParameter('restaurant',$restaurant)
        ;

        if ($search) {
            $qb
                ->andWhere('(UPPER(u.firstName) like :search or UPPER(u.lastName) like :search or UPPER(u.email) like :search or UPPER(u.phone) like :search)')
                ->setParameter('search', "%".strtoupper($search)."%")
            ;
        }

        return $qb->getQuery()->getResult();
    }
}
