board_additional_sale_library:
    path:  /additionalsale/library
    defaults: { _controller: ClabBoardBundle:AdditionalSale:library }

board_additional_sale_library_list:
    path:  /additionalsale/library-list
    defaults: { _controller: ClabBoardBundle:AdditionalSale:libraryList }

board_additional_sale_create:
    path:  /additionalsale/create
    defaults: { _controller: ClabBoardBundle:AdditionalSale:create }

board_additional_sale_edit:
    path:  /additionalsale/edit/{slug}
    defaults: { _controller: ClabBoardBundle:AdditionalSale:edit, slug: null }

board_additional_sale_delete:
    path:  /additionalsale/delete/{slug}
    defaults: { _controller: ClabBoardBundle:AdditionalSale:delete }

board_additional_sale_duplicate:
    path:  /additionalsale/duplicate/{slug}
    defaults: { _controller: ClabBoardBundle:AdditionalSale:duplicate }

board_additional_sale_assign_product:
    path:  /additionalsale/assign/{slug}
    defaults: { _controller: ClabBoardBundle:AdditionalSale:assignProducts }
