board_apps_library_restaurant:
    path:  /apps/mes-applications
    defaults: { _controller: ClabBoardBundle:Apps:myLibrary }

board_apps_library:
    path:  /apps/les-applications
    defaults: { _controller: ClabBoardBundle:Apps:library }

board_app_remove:
    path: /apps/mes-applications/desactiver/{slug}
    defaults: { _controller: ClabBoardBundle:Apps:removeApp }

board_app_add:
    path: /apps/mes-applications/activer/{slug}
    defaults: { _controller: ClabBoardBundle:Apps:addApp }
