board_appstore_website:
    path:  /website
    defaults: { _controller: ClabBoardBundle:Appstore:website }

board_appstore_widget:
    path:  /widget
    defaults: { _controller: ClabBoardBundle:Appstore:widget }

board_appstore_iframe:
    path:  /embed
    defaults: { _controller: ClabBoardBundle:Appstore:iframe }

board_appstore_app:
    path:  /app
    defaults: { _controller: ClabBoardBundle:Appstore:app }

board_appstore_app_deal:
    path:  /app/interest
    defaults: { _controller: ClabBoardBundle:Appstore:appDeal }

board_appstore_settings:
    path:  /settings/appstore
    defaults: { _controller: ClabBoardBundle:Appstore:settings }

board_appstore_print:
    path:  /impression
    defaults: { _controller: ClabBoardBundle:Appstore:print }
