board_caisse_session_library:
    path:  /sessions
    defaults: { _controller: ClabBoardBundle:Caisse:library }

board_caisse_session_library_list:
    path:  /sessions-list
    defaults: { _controller: ClabBoardBundle:Caisse:libraryList }

board_caisse_session_edit:
    path:  /sessions/edit/{id}
    defaults: { _controller: ClabBoardBundle:Caisse:edit }

board_caisse_settings:
    path:  /settings
    defaults: { _controller: ClabBoardBundle:Caisse:caisseSettings }