board_client_reporting:
    path:  /reporting
    defaults: { _controller: ClabBoardBundle:Client:reporting }

board_client_edit_restaurant:
    path:  /restaurant/edit/{slug}
    defaults: { _controller: ClabBoardBundle:Client:editRestaurant }

board_client_settings:
    path:  /settings
    defaults: { _controller: ClabBoardBundle:Client:settings }

board_client_settings_social:
    path:  /settings/social
    defaults: { _controller: ClabBoardBundle:Client:socialSettings }

board_client_company:
    path: /company
    defaults: { _controller: ClabBoardBundle:Client:editCompany, companyId: null }

board_client_edit_company:
    path: /company/edit/{companyId}
    defaults: { _controller: ClabBoardBundle:Client:companyModal, companyId: null }

board_client_charge_company:
    path: /company/charge/{companyId}
    defaults: { _controller: ClabBoardBundle:Client:chargeCompany, companyId: null }

board_client_loyalty_config:
    path: /loyalty
    defaults: { _controller: ClabBoardBundle:Loyalty:editLoyaltyConfig}

board_client_settings_suggestions:
    path:  /suggestions
    defaults: { _controller: ClabBoardBundle:Client:suggestions }

board_client_following:
    path: /orders
    defaults: { _controller: ClabBoardBundle:Client:orders }

board_canceled_order:
    path: /canceled
    defaults: { _controller: ClabBoardBundle:Client:canceledOrder}

board_preparation_canceled_order:
    path: /delivery
    defaults: { _controller: ClabBoardBundle:Client:preparationStateChangeOrder}

board_client_following_updated:
    path: /orders/updated
    defaults: { _controller: ClabBoardBundle:Client:orderJson}

board_client_following_by_restaurant:
    path: /orders/restaurant
    defaults: { _controller: ClabBoardBundle:Client:ordersByRestaurant}

board_client_following_by_date:
    path: /orders/date
    defaults: { _controller: ClabBoardBundle:Client:ordersByDate}

board_client_following_by_type:
    path: /orders/type
    defaults: { _controller: ClabBoardBundle:Client:ordersByType}