board_coupon_library:
    path:  /coupons/library
    defaults: { _controller: ClabBoardBundle:Coupon:library }

board_coupon_library_list:
    path:  /coupons/library-list
    defaults: { _controller: ClabBoardBundle:Coupon:libraryList }

board_coupon_edit:
    path:  /coupons/edit/{slug}
    defaults: { _controller: ClabBoardBundle:Coupon:edit, slug: null }

board_coupon_delete:
    path:  /coupons/delete/{slug}
    defaults: { _controller: ClabBoardBundle:Coupon:delete }
