board_delivery:
    path:  /delivery
    defaults: { _controller: ClabBoardBundle:Delivery:dashboard }

board_delivery_toggle:
    path:  /delivery/toggle
    defaults: { _controller: ClabBoardBundle:Delivery:toggle }

board_delivery_zones:
    path:  /delivery/zones
    defaults: { _controller: ClabBoardBundle:Delivery:zones }

board_delivery_zones_add:
    path:  /delivery/zones/add
    defaults: { _controller: ClabBoardBundle:Delivery:zonesAdd }

board_delivery_zones_edit:
    path:  /delivery/zones/edit
    defaults: { _controller: ClabBoardBundle:Delivery:zonesEdit }

board_delivery_zones_delete:
    path:  /delivery/zones/{slug}/delete
    defaults: { _controller: ClabBoardBundle:Delivery:zonesRemove }

board_delivery_day_view:
    path: /delivery/day_view/{timestamp}
    defaults: { _controller: ClabBoardBundle:Delivery:dayView, timestamp: null }

board_delivery_schedule_create:
    path: /delivery/schedule-create
    defaults: { _controller: ClabBoardBundle:Delivery:scheduleCreate }

board_delivery_schedule_edit:
    path: /delivery/schedule-edit/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:scheduleEdit, id: null }

board_delivery_schedule_edit_event:
    path: /delivery/schedule-edit-event/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:scheduleEditEvent, id: null }

board_delivery_schedule_delete:
    path: /delivery/schedule-delete/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:scheduleDelete }

board_delivery_calendar_edit:
    path: /delivery/calendar-edit/{timestamp}/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:calendarEdit }

board_delivery_day_create:
    path: /delivery/day-create/{value}/{cancel}
    defaults: { _controller: ClabBoardBundle:Delivery:dayCreate }

board_delivery_day_edit:
    path: /delivery/day-edit/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:dayEdit }

board_delivery_day_delete:
    path: /delivery/day-delete/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:dayDelete }

board_delivery_day_cancel_recurrent:
    path: /delivery/day-cancel-recurrent/{timestamp}/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:dayCancelRecurrent, id: null }

board_delivery_deliveryman_list:
    path: /delivery/deliverymen
    defaults: { _controller: ClabBoardBundle:Delivery:deliveryManList }

board_delivery_deliveryman_switch_deliveryday:
    path: /delivery/deliveryman-switch-deliveryday
    defaults: { _controller: ClabBoardBundle:Delivery:deliveryManSwitchDeliveryDay }

board_delivery_deliverycart_list:
    path: /delivery/deliverycart
    defaults: { _controller: ClabBoardBundle:Delivery:deliveryCartList }

board_delivery_deliverycart_list_content:
    path: /delivery/deliverycart-content
    defaults: { _controller: ClabBoardBundle:Delivery:deliveryCartListContent }

board_delivery_deliverycart_edit:
    path: /delivery/deliverycart-edit/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:deliveryCartEdit, id: null }

board_delivery_deliverycart_delete:
    path: /delivery/deliverycart-delete/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:deliveryCartDelete }

board_delivery_deliveryman_add:
    path: /delivery/delivery-man/add
    defaults: { _controller: ClabBoardBundle:Delivery:addDeliveryMan }

board_delivery_deliveryman_changestate:
    path: /delivery/delivery-man/change-state/{id}
    defaults: { _controller: ClabBoardBundle:Delivery:changeStateDeliveryMan }
