board_pincode_library_list:
    path:  /pincodes
    defaults: { _controller: ClabBoardBundle:User:pincodeLibraryList }

board_pincode_edit:
    path:  /pincode/edit/{id}
    defaults: { _controller: ClabBoardBundle:User:pincodeEdit, id: null }

board_pincode_delete:
    path:  /pincode/delete/{id}
    defaults: { _controller: ClabBoardBundle:User:pincodeDelete }
