board_review_library:
    path:  /commentaires/library
    defaults: { _controller: ClabBoardBundle:Review:library }

board_review_library_list:
    path:  /commentaires/library-list
    defaults: { _controller: ClabBoardBundle:Review:libraryList }

board_review_edit:
    path:  /commentaires/edit/{id}
    defaults: { _controller: ClabBoardBundle:Review:edit, id: null }

board_review_delete:
    path:  /commentaires/delete/{id}
    defaults: { _controller: ClabBoardBundle:Review:delete }

board_review_view:
    path:  /commentaires/view/{id}
    defaults: { _controller: ClabBoardBundle:Review:view }
