board_staff_library_list:
    path:  /staffs/library-list
    defaults: { _controller: ClabBoardBundle:User:staffLibraryList }

board_staff_edit:
    path:  /staff-edit/{id}
    defaults: { _controller: ClabBoardBundle:User:staffEdit, id: null }

board_staff_delete:
    path:  /staff-delete/{id}
    defaults: { _controller: ClabBoardBundle:User:staffDelete }

board_staff_update_position:
    path:  /staff-update-position
    defaults: { _controller: ClabBoardBundle:User:staffUpdatePosition }
