## Profile ##
board_restaurant_profile:
    path:  /infos
    defaults: { _controller: ClabBoardBundle:Store:profile }

board_restaurant_preorder:
    path:  /preorder
    defaults: { _controller: ClabBoardBundle:Store:preorder }

board_restaurant_settings_orders:
    path:  /settings/orders
    defaults: { _controller: ClabBoardBundle:Store:settingsOrder }

board_restaurant_extra_making_time:
    path:  /extra-making-time
    defaults: { _controller: ClabBoardBundle:Store:extraMakingTime }

board_catalog_import:
    path:  /import-catalog
    defaults: { _controller: ClabBoardBundle:Store:importCatalog }

board_restaurant_import:
    path:  /import-restaurant
    defaults: { _controller: ClabBoardBundle:Store:importRestaurant }

## Timesheet ##
board_restaurant_planning:
    path:  /planning
    defaults: { _controller: ClabBoardBundle:Planning:planning }

board_restaurant_planning_close:
    path:  /planning/close
    defaults: { _controller: ClabBoardBundle:Planning:close }

board_restaurant_planning_change:
    path:  /planning/change
    defaults: { _controller: ClabBoardBundle:Planning:change }

board_restaurant_planning_edit:
    path:  /planning/edit/{id}
    defaults: { _controller: ClabBoardBundle:Planning:edit, id: null }

board_restaurant_planning_delete:
    path:  /planning/delete/{id}
    defaults: { _controller: ClabBoardBundle:Planning:delete }

board_foodtruck_planning:
    path:  /foodtruck/planning
    defaults: { _controller: ClabBoardBundle:Planning:foodtruck }

board_foodtruck_planning_list:
    path:  /foodtruck/planning-list
    defaults: { _controller: ClabBoardBundle:Planning:foodtruckList }

board_foodtruck_create_address:
    path:  /foodtruck/create-address
    defaults: { _controller: ClabBoardBundle:Planning:createAddress }

board_foodtruck_delete_address:
    path:  /foodtruck/delete-address/{id}
    defaults: { _controller: ClabBoardBundle:Planning:deleteAddress }

board_foodtruck_edit_event:
    path:  /foodtruck/edit-event/{id}
    defaults: { _controller: ClabBoardBundle:Planning:editEvent, id: null }

board_foodtruck_planning_calender_edit:
    path:  /foodtruck/calendar-edit/{date}/{id}
    defaults: { _controller: ClabBoardBundle:Planning:calendarEdit }

board_foodtruck_planning_quick_close:
    path:  /foodtruck/quick-close/{date}/{id}
    defaults: { _controller: ClabBoardBundle:Planning:quickClose }

board_foodtruck_settings_order:
    path:  /foodtruck/order
    defaults: { _controller: ClabBoardBundle:Planning:settingsOrder }


