board_subscription_upgrade:
    path:  /upgrade
    defaults: { _controller: ClabBoardBundle:Upgrade:upgrade }

board_subscription_upgrade_pay_plan:
    path:  /upgrade/pay/plan/{slug}
    defaults: { _controller: ClabBoardBundle:Upgrade:payUpgradeSubscription }

board_subscription_customer_pay_existing:
    path:   /upgrade/{idPlan}/{idCard}
    defaults:  { _controller: ClabBoardBundle:Upgrade:upgradeExistingCard }
