board_user_database_library:
    path:  /user-database/library
    defaults: { _controller: ClabBoardBundle:UserDataBase:library }

board_user_database_list:
    path:  /user-database/library-list
    defaults: { _controller: ClabBoardBundle:UserDataBase:libraryList }

board_user_database_edit:
    path:  /user-database/edit/{id}
    defaults: { _controller: ClabBoardBundle:UserDataBase:edit, id: null }

board_user_database_delete:
    path:  /user-database/delete/{id}
    defaults: { _controller: ClabBoardBundle:UserDataBase:delete }
