## Users ##
board_user_library:
    path:  /users/library
    defaults: { _controller: ClabBoardBundle:User:library }

board_user_library_list:
    path:  /users/library-list
    defaults: { _controller: ClabBoardBundle:User:libraryList }

board_user_add:
    path:  /users/add
    defaults: { _controller: ClabBoardBundle:User:add }

board_user_pincode_add:
    path:  /users/pincode/add
    defaults: { _controller: ClabBoardBundle:User:addPinCode }

board_user_request:
    path:  /users/request
    defaults: { _controller: ClabBoardBundle:User:request }

board_user_request_resend:
    path:  /users/request-resend/{id}
    defaults: { _controller: ClabBoardBundle:User:requestResend }

board_user_edit:
    path:  /users/edit/{id}
    defaults: { _controller: ClabBoardBundle:User:edit }

board_user_edit_password:
    path:  /users/edit-password/{id}
    defaults: { _controller: ClabBoardBundle:User:editPassword }

board_user_remove:
    path:  /users/remove/{id}
    defaults: { _controller: ClabBoardBundle:User:remove }


## User chainstore ##
board_user_chainstore_library:
    path:  /users/client/library
    defaults: { _controller: ClabBoardBundle:UserChainStore:library }

board_user_chainstore_library_list:
    path:  /users/client/library-list
    defaults: { _controller: ClabBoardBundle:UserChainStore:libraryList }

board_user_chainstore_add:
    path:  /users/client/add
    defaults: { _controller: ClabBoardBundle:UserChainStore:add }

board_user_chainstore_pincode_add:
    path:  /users/client/pincode/add
    defaults: { _controller: ClabBoardBundle:UserChainStore:addPinCode }

board_user_chainstore_edit:
    path:  /users/client/edit/{id}
    defaults: { _controller: ClabBoardBundle:UserChainStore:edit }

board_user_chainstore_edit_password:
    path:  /users/client/edit-password/{id}
    defaults: { _controller: ClabBoardBundle:UserChainStore:editPassword }

board_user_chainstore_remove:
    path:  /users/client/remove/{id}
    defaults: { _controller: ClabBoardBundle:UserChainStore:remove }
