api_rest_product_category_from_chainstore:
    path:  /restaurant/{id}
    defaults: { _controller: ClabApiBundle:RestProductCategory:getForRestaurant, _format: json }
    methods: [GET]

api_rest_product_category_from_chainstore:
    path:  /chainstore/{id}
    defaults: { _controller: ClabApiBundle:RestProductCategory:getForChainStore, _format: json }
    methods: [GET]

api_rest_product_category_new_for_restaurant:
    path:  /restaurant/{id}/create
    defaults: { _controller: ClabApiBundle:RestProductCategory:newForRestaurant, _format: json }
    methods: [POST]

api_rest_product_category_new_for_chainstore:
    path:  /chainstore/{id}/create
    defaults: { _controller: ClabApiBundle:RestProductCategory:newForChainStore, _format: json }
    methods: [POST]

api_rest_product_category_edit:
    path:  /{id}/edit
    defaults: { _controller: ClabApiBundle:RestProductCategory:edit, _format: json }
    methods: [PUT,PATCH]

api_rest_product_category_products:
    path:  /{id}/remove
    defaults: { _controller: ClabApiBundle:RestProductCategory:delete, _format: json }
    methods: [DELETE]

api_rest_product_category_get_one:
    path:  /{categoryId}
    defaults: { _controller: ClabApiBundle:RestProductCategory:get, _format: json }
    methods: [GET]