api_rest_coupon_list:
    path:  /{restaurantId}
    defaults: { _controller: ClabApiBundle:RestCoupon:getCoupons, _format: json }
    methods: [GET]

api_rest_coupon_new:
    path:  /new/{restaurantId}
    defaults: { _controller: ClabApiBundle:RestCoupon:new, _format: json }
    methods: [POST]

api_rest_product_edit:
    path:  /edit/{id}
    defaults: { _controller: ClabApiBundle:RestCoupon:edit, _format: json }
    methods: [PUT,PATCH]
