#
api_rest_delivery_list:
    path:  /list/{restaurantId}
    defaults: { _controller: ClabApiBundle:RestDelivery:listDelivery, _format: json }
    requirements:
          restaurantId: \d+
    methods: [GET]
#
api_rest_delivery_by_id:
    path:  /{id}
    defaults: { _controller: ClabApiBundle:RestDelivery:getOneById, _format: json }
    requirements:
          id: \d+
    methods: [GET]

#
api_rest_delivery_state:
    path:  /state/{id}
    defaults: { _controller: ClabApiBundle:RestDelivery:getState, _format: json }
    requirements:
          id: \d+
    methods: [GET]
#
api_rest_set_delivery_state:
    path:  /state/{id}
    defaults: { _controller: ClabApiBundle:RestDelivery:setState, _format: json }
    requirements:
          id: \d+
    methods: [POST]

#
api_rest_set_delivery_man_to_delivery:
    path:  /{id}/deliveryMan/{deliveryManId}
    defaults: { _controller: ClabApiBundle:RestDelivery:setDeliveryManToDelivery, _format: json }
    requirements:
          id: \d+
          deliveryManId : \d+
    methods: [POST]

#
api_rest_remove_delivery_man_from_delivery:
    path:  /{id}/deliveryMan
    defaults: { _controller: ClabApiBundle:RestDelivery:removeDeliveryManFromDelivery, _format: json }
    requirements:
          id: \d+
          deliveryManId : \d+
    methods: [DELETE]

##deliveryMen Section

#
api_rest_deliveryMan_list:
    path:  /deliveryMan/list/{restaurantId}
    defaults: { _controller: ClabApiBundle:RestDelivery:listDeliveryMan, _format: json }
    requirements:
          restaurantId: \d+
    methods: [GET]

#
api_rest_get_delivery_man_connected:
    path:  /deliveryMan/me
    defaults: { _controller: ClabApiBundle:RestDelivery:getDeliveryManMe, _format: json }
    requirements:
          id: \d+
    methods: [GET]
#
api_rest_get_delivery_man_by_id:
    path:  /deliveryMan/{id}
    defaults: { _controller: ClabApiBundle:RestDelivery:getDeliveryMan, _format: json }
    requirements:
          id: \d+
    methods: [GET]
#
api_rest_create_delivery_man:
    path:  /deliveryMan
    defaults: { _controller: ClabApiBundle:RestDelivery:createDeliveryMan, _format: json }
    requirements:
          id: \d+
    methods: [POST]
#
api_rest_edit_delivery_man:
    path:  /deliveryMan/{id}
    defaults: { _controller: ClabApiBundle:RestDelivery:editDeliveryMan, _format: json }
    requirements:
          id: \d+
    methods: [PUT]

#
api_rest_remove_delivery_man:
    path:  /deliveryMan/{id}
    defaults: { _controller: ClabApiBundle:RestDelivery:removeDeliveryMan, _format: json }
    requirements:
          id: \d+
    methods: [DELETE]

#
api_rest_delivery_check:
    path:  /check
    defaults: { _controller: ClabApiBundle:RestDelivery:getCheck, _format: json }
    methods: [GET]

