api_rest_meal_get_restaurant:
    path:  /restaurant/{restaurantId}
    defaults: { _controller: ClabApiBundle:RestMeal:getAvailableforRestaurant, _format: json }
    methods: [GET]

api_rest_meal_get_menu:
    path:  /menu/{menuId}
    defaults: { _controller: ClabApiBundle:RestMeal:getAvailableforRestaurantMenu, _format: json }
    methods: [GET]

api_rest_meal_list_for_menu:
    path:  /menu/{menuId}/all
    defaults: { _controller: ClabApiBundle:RestMeal:getForRestaurantMenu, _format: json }
    methods: [GET]

api_rest_meal_list_for_chainstore:
    path:  /chainstore/{chainstoreId}
    defaults: { _controller: ClabApiBundle:RestMeal:getForChainStore, _format: json }
    methods: [GET]

api_rest_meal_add_slot:
    path:  /{mealId}/slot/{slotId}
    defaults: { _controller: ClabApiBundle:RestMeal:addSlotToMeal, _format: json }
    methods: [POST]

api_rest_meal_remove_slot:
    path:  /{mealId}/slot/{slotId}
    defaults: { _controller: ClabApiBundle:RestMeal:removeSlotFromMeal, _format: json }
    methods: [DELETE]

api_rest_meal_create_slot_for_restaurant:
    path:  /restaurant/{restaurantId}/slot
    defaults: { _controller: ClabApiBundle:RestMeal:createMealSlotForRestaurant, _format: json }
    methods: [POST]

api_rest_meal_create_slot_for_chainstore:
    path:  /chainstore/{chainstoreId}/slot
    defaults: { _controller: ClabApiBundle:RestMeal:createMealSlotForChainStore, _format: json }
    methods: [POST]

api_rest_meal_get_slot_for_restaurant:
    path:  /restaurant/{restaurantId}/slot
    defaults: { _controller: ClabApiBundle:RestMeal:getSlotForRestaurant, _format: json }
    methods: [GET]

api_rest_meal_get_slot_for_chainstore:
    path:  /chainstore/{chainstoreId}/slot
    defaults: { _controller: ClabApiBundle:RestMeal:getSlotForChainStore, _format: json }
    methods: [GET]

api_rest_meal_get:
    path:  /{mealId}
    defaults: { _controller: ClabApiBundle:RestMeal:getMeal, _format: json }
    methods: [GET]

api_rest_meal_delete:
    path:  /{mealId}
    defaults: { _controller: ClabApiBundle:RestMeal:remove, _format: json }
    methods: [DELETE]

api_rest_meal_delete_for_menu:
    path:  /{mealId}/menu/{menuId}
    defaults: { _controller: ClabApiBundle:RestMeal:removeForRestaurantMenu, _format: json }
    methods: [DELETE]