## Orders ##
api_rest_order_for_restaurant:
    path:  /restaurant/{id}/orders
    defaults: { _controller: ClabApiBundle:RestOrder:getForRestaurant, _format: json }
    methods: [GET]

api_rest_order_beetween_dates:
    path:  /orders/dates
    defaults: { _controller: ClabApiBundle:RestOrder:getBeetweenDates, _format: json }
    methods: [GET]

api_rest_order_ticket_for_restaurant:
    path:  /restaurant/{id}/ticket/orders
    defaults: { _controller: ClabApiBundle:RestOrder:getTicketForRestaurant, _format: json }
    methods: [GET]

api_rest_order_get:
    path:  /orders/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:get, _format: json }
    methods: [GET]

api_rest_order_cart:
    path:  /orders/cart/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:getCart, _format: json }
    methods: [GET]

api_rest_order_edit:
    path:  /orders/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:edit, _format: json }
    methods: [PUT, PATCH]

api_rest_order_remove:
    path:  /orders/remove/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:remove, _format: json }
    methods: [POST]

api_rest_order_close:
    path:  /orders/close/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:closeOrder, _format: json }
    methods: [POST]

api_rest_order_validate:
    path:  /orders/validate/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:validateOrder, _format: json }
    methods: [POST]

api_post_order_cart:
    path:  /orders/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:postOrderCart, _format: json }
    methods: [POST]

api_rest_order_get_slots:
    path:  /orders/slots/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:getSlotsFromCart, _format: json }
    methods: [GET]

api_rest_order_get_payment_methods:
    path:  /orders/paymentmethods/cart/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:getPaymentMethodsForCart, _format: json }
    methods: [GET]

api_rest_order_init:
    path:  /orders/init/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:initOrder, _format: json }
    methods: [POST]

api_rest_order_get_payzen_request:
    path:  /orders/payzenrequest/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:getPayzenRequest, _format: json }
    methods: [GET]

api_rest_order_edit_state:
    path: /order/state/edit/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:changeOrderState, _format: json }
    methods: [POST]

api_rest_order_caisse_edit_state:
    path: /order/caisse/state/edit/{id}
    defaults: { _controller: ClabApiBundle:RestOrder:changeOrderCaisseState, _format: json }
    methods: [POST]

api_rest_order_caisse_save:
    path: /order/caisse/save
    defaults: { _controller: ClabApiBundle:RestOrder:saveCaisseOrder, _format: json }
    methods: [POST]

api_rest_order_types:
    path: /ordertypes
    defaults: { _controller: ClabApiBundle:RestOrder:getOrderTypes, _format: json }
    methods: [GET]

api_rest_order_get_my_orders:
    path: /me/orders
    defaults: { _controller: ClabApiBundle:RestOrder:getMyOrders, _format: json }
    methods: [GET]