api_get_payment_methods:
    path:  /methods/{id}
    defaults: { _controller: ClabApiBundle:RestPayment:getPaymentMethods, _format: json }
    methods: [GET]

api_get_payment_cards:
    path:  /cards
    defaults: { _controller: ClabApiBundle:RestPayment:getCards, _format: json }
    methods: [GET]

api_post_payment_cards:
    path:  /cards
    defaults: { _controller: ClabApiBundle:RestPayment:postCards, _format: json }
    methods: [POST]

api_post_pay:
    path:  /{id}
    defaults: { _controller: ClabApiBundle:RestPayment:postPayment, _format: json }
    methods: [POST]