## POS Printer ##
api_rest_post_printer_list:
    path:  /restaurant/{id}/posprinters
    defaults: { _controller: ClabApiBundle:RestPOSPrinter:list, _format: json }
    methods: [GET]

api_rest_post_printer_get:
    path:  /restaurant/{idRestaurant}/posprinters/{id}
    defaults: { _controller: ClabApiBundle:RestPOSPrinter:get, _format: json }
    methods: [GET]

api_rest_post_printer_new:
    path:  /restaurant/{id}/new/posprinters
    defaults: { _controller: ClabApiBundle:RestPOSPrinter:new, _format: json }
    methods: [POST]

api_rest_post_printer_edit:
    path:  /restaurant/{idRestaurant}/posprinters/edit/{id}
    defaults: { _controller: ClabApiBundle:RestPOSPrinter:edit, _format: json }
    methods: [PUT,PATCH]

api_rest_post_printer_delete:
    path:  /restaurant/{idRestaurant}/posprinters/delete/{id}
    defaults: { _controller: ClabApiBundle:RestPOSPrinter:delete, _format: json }
    methods: [DELETE]
