## Social ##
api_rest_review_list:
    path:  /reviews/{id}
    defaults: { _controller: ClabApiBundle:RestReview:list, _format: json }
    methods: [GET]

api_rest_review_new:
    path:  /reviews/{id}
    defaults: { _controller: ClabApiBundle:RestReview:new, _format: json }
    methods: [POST]

api_rest_review_upvote:
    path:  /reviews/{reviewId}/{voteType}
    defaults: { _controller: ClabApiBundle:RestReview:vote, _format: json }
    methods: [POST]

api_rest_review_delete_all:
    path:  /reviews/{id}
    defaults: { _controller: ClabApiBundle:RestReview:deleteAll, _format: json }
    methods: [DELETE]
