#
api_rest_search_multiple:
    path: /
    defaults: { _controller: ClabApiBundle:RestSearch:searchMultiple, _format: json }
    requirements:
            search: \d+
    methods: [GET]

api_rest_search_users:
    path:  /users
    defaults: { _controller: ClabApiBundle:RestUser:search, _format: json }
    methods: [GET]

api_rest_search_user_by_id:
    path:  /users/{id}
    defaults: { _controller: ClabApiBundle:RestUser:getUserById, _format: json }
    requirements:
              id: \d+
    methods: [GET]