## Social ##
api_rest_social_post_list:
    path:  /restaurant/{restaurantId}/socialposts
    defaults: { _controller: ClabApiBundle:RestSocial:postList, _format: json }
    methods: [GET]

api_rest_social_post_new:
    path:  /restaurant/{restaurantId}/socialposts
    defaults: { _controller: ClabApiBundle:RestSocial:postNew, _format: json }
    methods: [POST]

api_rest_social_post_delete:
    path:  /restaurant/{restaurantId}/socialposts/{id}
    defaults: { _controller: ClabApiBundle:RestSocial:postDelete, _format: json }
    methods: [DELETE]
