api_rest_find_user_by_phone:
    path:  /phone-search
    defaults: { _controller: ClabApiBundle:RestUser:findUsersInfoByPhone, _format: json }
    methods: [GET,OPTIONS]

api_rest_reverse_user_by_phones:
    path:  /phone-search
    defaults: { _controller: ClabApiBundle:RestUser:findUsersIdByPhoneArray, _format: json }
    methods: [POST]

api_rest_reverse_user_by_fb:
    path:  /fb-search
    defaults: { _controller: ClabApiBundle:RestUser:findUsersIdByFBArray, _format: json }
    methods: [POST]

api_rest_user_authenticate:
    path:  /authenticate
    defaults: { _controller: ClabApiBundle:RestUser:login, _format: json }
    methods: [POST]

api_rest_users_list:
    path:  /list
    defaults: { _controller: ClabApiBundle:RestUser:getusers, _format: json }
    methods: [GET]

api_rest_user_logout:
    path:  /logout
    defaults: { _controller: ClabApiBundle:RestUser:logout, _format: json }
    methods: [POST]

api_rest_user_restaurants:
    path:  /restaurants
    defaults: { _controller: ClabApiBundle:RestUser:restaurants, _format: json }
    methods: [GET]

api_rest_user_edit:
    path:  /profile
    defaults: { _controller: ClabApiBundle:RestUser:edit, _format: json }
    methods: [PUT, PATCH]

api_rest_user_edit_cover:
    path:  /profile/cover
    defaults: { _controller: ClabApiBundle:RestUser:editCover, _format: json }
    methods: [POST]

api_rest_user_reset_password:
    path:  /password/reset
    defaults: { _controller: ClabApiBundle:RestUser:resetPassword, _format: json }
    methods: [POST]

api_rest_user_pincode_login:
    path:  /pin/{restaurant}/login
    defaults: { _controller: ClabApiBundle:RestUser:loginPinCode, _format: json }
    methods: [POST]

api_rest_user_friendlist_add:
    path:  /friendlist
    defaults: { _controller: ClabApiBundle:RestUser:addUserToFriendList, _format: json }
    methods: [POST]

api_rest_user_friendlist_remove:
    path:  /friendlist
    defaults: { _controller: ClabApiBundle:RestUser:removeUserToFriendList, _format: json }
    methods: [DELETE]

api_rest_user_friendlist_add_from_fb:
    path:  /friendlist/add/facebook
    defaults: { _controller: ClabApiBundle:RestUser:addUserToFriendListFromFB, _format: json }
    methods: [POST]

api_rest_user_friendlist_add_from_emails:
    path:  /friendlist/add/emails
    defaults: { _controller: ClabApiBundle:RestUser:addUserToFriendListFromEmail, _format: json }
    methods: [POST]

api_rest_user_friendlist_add_from_phone:
    path:  /friendlist/add/phone
    defaults: { _controller: ClabApiBundle:RestUser:addUserToFriendListFromPhone, _format: json }
    methods: [POST]

api_rest_user_find_images:
    path:  /images/public/{id}
    defaults: { _controller: ClabApiBundle:RestUser:findAllImageFromUser, _format: json }
    methods: [POST]

api_rest_user_post_image:
    path:  /image/post/{entityId}/{userId}
    defaults: { _controller: ClabApiBundle:RestUser:uploadImageInRestaurant, _format: json }
    methods: [POST]

api_rest_user_validate:
    path:  /validate
    defaults: { _controller: ClabApiBundle:RestUser:validateLogin, _format: json }
    methods: [POST]

api_rest_user_get_database:
    path:  /database/{restaurantId}
    defaults: { _controller: ClabApiBundle:RestUser:getUserDatabase, _format: json }
    methods: [GET]

api_rest_user_add_database:
    path:  /database/{restaurantId}
    defaults: { _controller: ClabApiBundle:RestUser:addUserDatabase, _format: json }
    methods: [POST]

api_rest_user_edit_database:
    path:  /database/{restaurantId}/{userId}
    defaults: { _controller: ClabApiBundle:RestUser:editUserDatabase, _format: json }
    methods: [PUT,PATCH]

api_rest_user_delete_database:
    path:  /database/{restaurantId}/{userId}
    defaults: { _controller: ClabApiBundle:RestUser:removeUserDatabase, _format: json }
    methods: [DELETE]

#
api_rest_restaurant_get_favorites:
    path:  /favorites/restaurant
    defaults: { _controller: ClabApiBundle:RestUser:getFavorites, _format: json }
    methods: [GET]
#
api_rest_restaurant_add_favorite:
    path:  /favorites/restaurant/{restaurant}
    defaults: { _controller: ClabApiBundle:RestUser:addFavorite, _format: json }
    methods: [POST]
#
api_rest_restaurant_remove_favorite:
    path:  /favorites/restaurant/{restaurant}
    defaults: { _controller: ClabApiBundle:RestUser:removeFavorite, _format: json }
    methods: [DELETE]

api_rest_restaurant_get_favorites_searches:
    path:  /favorites/search
    defaults: { _controller: ClabApiBundle:RestUser:getFavoriteSearches, _format: json }
    methods: [GET]
#
api_rest_restaurant_add_favorite_search:
    path:  /favorites/search
    defaults: { _controller: ClabApiBundle:RestUser:addFavoriteSearch, _format: json }
    methods: [POST]
#
api_rest_restaurant_remove_favorite_search:
    path:  /favorites/search/{searchKey}
    defaults: { _controller: ClabApiBundle:RestUser:removeFavoriteSearch, _format: json }
    methods: [DELETE]
#
api_rest_user_get:
    path:  /{email}
    defaults: { _controller: ClabApiBundle:RestUser:getUser, _format: json }
    methods: [GET]
#
api_rest_user_get_reviews:
    path:  /{email}/reviews
    defaults: { _controller: ClabApiBundle:RestUser:getReviews, _format: json }
    methods: [GET]
#
api_rest_friends:
    path:  /{email}/friends
    defaults: { _controller: ClabApiBundle:RestUser:getFriends, _format: json }
    methods: [GET]

api_rest_addresses:
    path:  /addresses
    defaults: { _controller: ClabApiBundle:RestUser:postAddress, _format: json }
    methods: [POST]

api_rest_followers:
    path: /followers
    defaults: { _controller: ClabApiBundle:RestUser:getFollowers, _format: json }
    methods: [GET]

api_rest_add_followed:
    path: /follow/{userId}
    defaults: { _controller: ClabApiBundle:RestUser:postFollowed, _format: json }
    methods: [POST]

api_rest_remove_followed:
    path: /unfollow/{userId}
    defaults: { _controller: ClabApiBundle:RestUser:removeFollowed, _format: json }
    methods: [DELETE]