Clab\TaxonomyBundle\Entity\Term:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        created:
            expose: true
        is_online:
            expose: true
            accessor:
                getter: isOnline
                setter: setIsOnline
        name:
            expose: true
            read_only: true
        slug:
            expose: true
            read_only: true
        images:
            expose: true
            read_only: true