<?php

namespace Clab\ShopBundle\Repository;

/**
 * LoyaltyConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoyaltyConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
