<?php

namespace Clab\ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderTypeRepository extends EntityRepository
{
}
