Clab\BoardBundle\Entity\UserDataBase:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        id:
            expose: true
            read_only: true
            groups: [app,public,pro]
        user:
            expose: true
            read_only: true
            groups: [app,public,pro]
        email:
            expose: true
            read_only: true
            groups: [app,public,pro]
        note:
            expose: true
            read_only: true
            groups: [app,public,pro]
        company:
            expose: true
            read_only: true
            groups: [app,public,pro]
        subscribedNewsletter:
            expose: true
            read_only: true
            groups: [app,public,pro]