Clab\BoardBundle\Entity\Company:
    exclusion_policy: ALL
    access_type: public_method
    properties:
        name:
            expose: true
            read_only: true
            groups: [app,pro]
        address:
            expose: true
            read_only: true
            groups: [app,pro]
        phone:
            expose: true
            read_only: true
            groups: [app,pro]
        email:
            expose: true
            read_only: true
            groups: [app,pro]
        description:
            expose: true
            read_only: true
            groups: [app,pro]
        companyPayment:
            expose: true
            read_only: true
            groups: [app,pro]
        balance:
            expose: true
            read_only: true
            groups: [app,pro]
        nextDueDate:
            expose: true
            read_only: true
            groups: [app,pro]
        isOnline:
            expose: true
            read_only: true
            accessor:
                getter: isOnline
            groups: [app,pro]
