parameters:
    clab_taxonomy.manager.class: Clab\TaxonomyBundle\Service\Manager

services:
    clab_taxonomy.manager:
        class: %clab_taxonomy.manager.class%
        arguments: [ @doctrine.orm.entity_manager, @service_container ]

    clab_taxonomy.term_extension:
        class: Clab\TaxonomyBundle\Twig\TermExtension
        tags:
            - { name: twig.extension }