clab_call_center_homepage:
    path:     /{page}
    defaults: { _controller: ClabCallCenterBundle:Default:client , page: 0}
    requirements:
        page: \d+

clab_call_center_choose_customer:
    path:     /choose-customer/{id}
    defaults: { _controller: ClabCallCenterBundle:Default:chooseCustomer }

clab_call_center_order_type:
    path:     /ordertype
    defaults: { _controller: ClabCallCenterBundle:Default:orderType }

clab_call_center_restaurant_list:
    path:     /restaurant/list
    defaults: { _controller: ClabCallCenterBundle:Default:restaurantList }

clab_call_center_choose_restaurant:
    path:     /choose-restaurant/{id}
    defaults: { _controller: ClabCallCenterBundle:Default:chooseRestaurant }

clab_call_center_order:
    path:     /commande
    defaults: { _controller: ClabCallCenterBundle:Default:order }

clab_call_center_cart_add:
    path: /panier/add/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:addProductToCart }

clab_call_center_cart_clear:
    path: /panier/vider/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:clearCart }

clab_call_center_cart_update_quantity:
    path: /panier/update-quantity/{slug}/{hash}/{add}
    defaults: { _controller: ClabCallCenterBundle:Cart:updateQuantity, add: null }

clab_call_center_cart_update_sauces:
    path: /panier/sauces/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:updateSauces }

clab_call_center_cart_update_loyalties:
    path: /panier/{slug}/loyalties/{loyaltyId}
    defaults: { _controller: ClabCallCenterBundle:Cart:updateLoyalties }

clab_call_center_product_option_form:
    path: /panier/product-option-form/{slug}/{token}/{slot}
    defaults: { _controller: ClabCallCenterBundle:Cart:productOptionForm, token: null, slot: null }

clab_call_center_meal:
    path: /panier/formule/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:meal }

clab_call_center_meal_compose:
    path: /panier/formule/composer/{token}/{slot}/{choice}
    defaults: { _controller: ClabCallCenterBundle:Cart:mealCompose, slot: null, choice: null }

clab_call_center_cart_coupon:
    path: /panier/coupon/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:coupon }

clab_call_center_cart_coupon_remove:
    path: /panier/coupon/remove/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:couponRemove }

clab_call_center_cart_product_remove:
    path: /panier/produit/remove/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:removeProductFromCart }

clab_call_center_cart_meal_remove:
    path: /panier/formule/remove/{slug}
    defaults: { _controller: ClabCallCenterBundle:Cart:removeMealFromCart }

clab_call_center_cart_element_remove:
    path: /panier/element/remove/{slug}/{elementHash}
    defaults: { _controller: ClabCallCenterBundle:Cart:removeElementFromCart }

clab_call_center_recap:
    path: /restaurant/commande/recap
    defaults: { _controller: ClabCallCenterBundle:Order:order }

clab_call_center_card_add:
    path:  /commande/add-card/{userId}
    defaults: { _controller: ClabCallCenterBundle:Order:createCard }

clab_call_center_card_remove:
    path:  /commande/remove-card/{user}/{card}
    defaults: { _controller: ClabCallCenterBundle:Order:deleteCreditCard }

clab_call_center_card_list:
    path:  /commande/list-card/{user}
    defaults: { _controller: ClabCallCenterBundle:Order:listCards }

clab_call_center_order_receipt:
    path:  /commande/{hash}
    defaults: { _controller: ClabCallCenterBundle:Order:orderReceipt }

clab_call_center_check_user_phone:
    path:  /check-phone/{phone}
    defaults: { _controller: ClabCallCenterBundle:User:checkPhone }

clab_call_center_user_info:
    path:  /get-info/{userId}
    defaults: { _controller: ClabCallCenterBundle:User:userInfo }

clab_call_center_search:
    path:  /search
    defaults: { _controller: ClabCallCenterBundle:User:searchUsers }

clab_call_center_change_order_type:
    path:  /change-order-type
    defaults: { _controller: ClabCallCenterBundle:Default:changeOrderType }

clab_call_center_email_valid:
    path:  /check-email
    defaults: { _controller: ClabCallCenterBundle:Default:checkUserExist }