services:
    app_location.location_manager:
        class: Clab\LocationBundle\Service\LocationManager
        arguments: [ @service_container, @doctrine.orm.entity_manager ]

    app_location.address_listener:
        class: Clab\LocationBundle\Service\AddressListener
        arguments: [ @service_container ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate }
            - { name: doctrine.event_listener, event: postPersist, method: postPersist }

    app_location.place_listener:
        class: Clab\LocationBundle\Service\PlaceListener
        arguments: [ @service_container, @liip_imagine.cache.manager, %clab_location.api_domain% ]
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }

    app_location.event_listener:
        class: Clab\LocationBundle\Service\EventListener
        arguments: [ @service_container, @liip_imagine.cache.manager, %clab_location.api_domain% ]
        tags:
            - { name: doctrine.event_listener, event: postLoad, method: postLoad }

    location.place_manager:
        class: Clab\LocationBundle\Service\PlaceManager
        arguments: [ @service_container, @doctrine.orm.entity_manager, @router ]

    location.event_manager:
        class: Clab\LocationBundle\Service\EventManager
        arguments: [ @service_container, @doctrine.orm.entity_manager, @router ]
