Clab\DeliveryBundle\Entity\DeliveryPeriod:
    properties:
        #start:
        #    - NotBlank: ~
        #end:
        #    - NotBlank: ~

Clab\DeliveryBundle\Entity\DeliveryDay:
    properties:
        start:
            - NotBlank: ~
        end:
            - NotBlank: ~