clab_white_homepage:
    path:     /
    defaults: { _controller: ClabWhiteBundle:Order:chainStore }

clab_white_serp:
    path:     /recherche
    defaults: { _controller: ClabWhiteBundle:Order:serp }

clab_white_home:
    path: /restaurant/{slug}/commande
    defaults: { _controller: ClabWhiteBundle:Order:home }

clab_white_recap:
    path: /restaurant/{slug}/commande/recap/{day}
    defaults: { _controller: ClabWhiteBundle:Order:order, day: null }

clab_white_order_date_check:
    path: /restaurant/{slug}/commande/date/{date}
    defaults: { _controller: ClabWhiteBundle:Order:checkOrderDate, date: null }

clab_white_receipt:
    path:  /commande/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:orderReceipt }

clab_white_payment:
    path:  /paiement/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:orderPayment }

clab_white_switch_payment:
    path:  /order-switch-payment/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:switchPayment }

clab_white_switch_payment_online:
    path:  /order-switch-payment-online/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:switchPaymentOnline }

clab_white_card_add:
    path:  /commande/add-card/{user}
    defaults: { _controller: ClabWhiteBundle:Order:createCard }

clab_white_card_remove:
    path:  /commande/remove-card/{user}/{card}
    defaults: { _controller: ClabWhiteBundle:Order:deleteCreditCard }

clab_white_card_list:
    path:  /commande/list-card/{user}
    defaults: { _controller: ClabWhiteBundle:Order:listCards }

clab_white_user_login:
    path:  /login
    defaults: { _controller: ClabWhiteBundle:User:login }

clab_white_user_register:
    path:  /register
    defaults: { _controller: ClabWhiteBundle:User:register }


clab_white_cart_empty:
    path: /panier/empty/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:empty }

clab_white_cart_display:
    path: /panier/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:render }


clab_white_user_profile:
    path: /mon-profil
    defaults: { _controller: ClabWhiteBundle:User:profile }

clab_white_user_favorite_page:
    path: /mon-profil/mes-favoris
    defaults: { _controller: ClabWhiteBundle:User:favorite }

clab_white_user_address:
    path: /mon-profil/mes-adresses
    defaults: { _controller: ClabWhiteBundle:User:userAddress }

clab_white_user_add_address:
    path: /mon-profil/mes-adresses/ajouter
    defaults: { _controller: ClabWhiteBundle:User:addAddress }

clab_white_user_delete_address:
    path: /mon-profil/mes-adresses/delete/{id}
    defaults: { _controller: ClabWhiteBundle:User:deleteAddress, id: null }

clab_white_user_edit_address:
    path: /mon-profil/mes-adresses/modifier/{id}
    defaults: { _controller: ClabWhiteBundle:User:editAddress, id: null  }

clab_white_user_set_home_address:
    path: /mon-profil/mes-adresses/adresse-principale/{id}
    defaults: { _controller: ClabWhiteBundle:User:setHomeAddress, id: null }

clab_white_user_remove_home_address:
    path: /mon-profil/mes-adresses/supprimer-adresse-principale
    defaults: { _controller: ClabWhiteBundle:User:removeHomeAddress }

clab_white_user_orders:
    path: /mon-profil/mes-commandes
    defaults: { _controller: ClabWhiteBundle:User:orderHistory }

clab_white_user_reductions:
    path: /mon-profil/mes-reductions
    defaults: { _controller: ClabWhiteBundle:User:reductions }

clab_white_user_payments:
    path: /mon-profil/mes-moyens-de-paiement
    defaults: { _controller: ClabWhiteBundle:User:payment }

clab_white_cart_add:
    path: /panier/add/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:addProductToCart }

clab_white_cart_update_quantity:
    path: /panier/update-quantity/{slug}/{hash}/{quantity}
    defaults: { _controller: ClabWhiteBundle:Cart:updateQuantity, quantity: null }

clab_white_product_option_form:
    path: /panier/product-option-form/{slug}/{token}/{slot}
    defaults: { _controller: ClabWhiteBundle:Cart:productOptionForm, token: null, slot: null }

clab_white_meal:
    path: /panier/formule/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:meal }

clab_white_meal_compose:
    path: /panier/formule/composer/{token}/{slot}/{choice}
    defaults: { _controller: ClabWhiteBundle:Cart:mealCompose, slot: null, choice: null }

clab_white_cart_coupon:
    path: /panier/coupon/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:coupon }

clab_white_cart_coupon_remove:
    path: /panier/coupon/remove/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:couponRemove }

clab_white_cart_product_remove:
    path: /panier/produit/remove/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:removeProductFromCart }

clab_white_cart_meal_remove:
    path: /panier/formule/remove/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:removeMealFromCart }

clab_white_cart_element_remove:
    path: /panier/element/remove/{slug}/{elementHash}
    defaults: { _controller: ClabWhiteBundle:Cart:removeElementFromCart }

clab_white_order_home:
    path: /restaurant/{slug}/commande
    defaults: { _controller: ClabWhiteBundle:Order:home }

clab_white_order_recap:
    path: /restaurant/{slug}/commande/recap
    defaults: { _controller: ClabWhiteBundle:Order:order }
    defaults: { _controller: ClabWhiteBundle:Order:order }

clab_white_order_receipt:
    path:  /commande/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:orderReceipt }

clab_white_order_follow_state:
    path:  /commande/follow/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:orderFollow }
    methods: [GET]

clab_white_order_switch_payment:
    path:  /order-switch-payment/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:switchPayment }

clab_white_order_switch_payment_online:
    path:  /order-switch-payment-online/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:switchPaymentOnline }

clab_white_order_cancel:
    path:  /annulation-commande/{hash}
    defaults: { _controller: ClabWhiteBundle:Order:cancel }

clab_white_order_home_client:
    pattern: /chainstore/{slug}
    defaults: { _controller: ClabWhiteBundle:Order:chainStore }
    host: %embeddomain%

clab_additional_sale_product:
    path: /additionalsale/product/{slug}
    defaults: { _controller: ClabWhiteBundle:AdditionalSale:additionalSaleProduct }

clab_additional_sale_meal:
    path: /additionalsale/meal/{slug}
    defaults: { _controller: ClabWhiteBundle:AdditionalSale:additionalSaleMeal }

clab_additional_sale_get_option_form:
    path: /additionalsale/optionform/{slug}
    defaults: { _controller: ClabWhiteBundle:AdditionalSale:getAdditionalSaleOptionForm }

clab_cart_add_sale:
    path: /panier/additionalsale/add/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:addAdditionalSaleToCart }

clab_cart_add_sale_with_option:
    path: /panier/additionalsale/add/{slug}/{slugProd}
    defaults: { _controller: ClabWhiteBundle:Cart:addAdditionalSaleWithOptionToCart }

clab_cart_update_favorite_product:
    path: /user/favorite-product/{slug}/{add}
    defaults: { _controller: ClabWhiteBundle:User:updateFavoriteProduct }

clab_cart_update_sauces:
    path: /cart/sauces/{slug}
    defaults: { _controller: ClabWhiteBundle:Cart:updateSauces }

clab_cart_update_loyalties:
    path: /cart/{slug}/loyalties/{loyaltyId}
    defaults: { _controller: ClabWhiteBundle:Cart:updateLoyalties }