opauth_process:
    path: /opauth/{type}/callback
    defaults: { _controller: ClabSocialBundle:Opauth:callback }

opauth:
    path: /opauth/{type}/{params}
    defaults: { _controller: ClabSocialBundle:Opauth:opauth, params: null }

opauth_ttt:
    path: /opauth/{type}/{params}
    defaults: { _controller: ClabSocialBundle:Opauth:opauth, params: null }
    host: %clab_social.tttdomain%