services:
    clab.social_post_listener:
        class: Clab\SocialBundle\Listener\SocialPostListener
        arguments: [ @vich_uploader.templating.helper.uploader_helper, %clab_social.api_domain% ]
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    clab.social_manager:
        class: Clab\SocialBundle\Service\SocialManager
        arguments: [ @service_container, @doctrine.orm.entity_manager, @router ]
        scope: request