api_0_rest_get_cart:
    path:  /cart/{id}
    defaults: { _controller: ClabApiOldBundle:RestCart:getCart, _format: json }
    methods: [GET]

api_0_rest_create_cart:
    path:  /cart/create
    defaults: { _controller: ClabApiOldBundle:RestCart:create, _format: json }
    methods: [POST]

api_0_rest_meal_to_cart:
    path:  /cart/meal/add/{id}
    defaults: { _controller: ClabApiOldBundle:RestCart:addMealToCart, _format: json }
    methods: [GET]

api_0_add_product_to_cart:
    path:  /cart/product/add/{id}
    defaults: { _controller: ClabApiOldBundle:RestCart:addProductToCart, _format: json }
    methods: [POST]

api_0_remove_product_to_cart:
    path:  /cart/product/remove/{id}
    defaults: { _controller: ClabApiOldBundle:RestCart:removeProductFromCart, _format: json }
    methods: [POST]

api_0_cart_empty:
    path:  /cart/empty/{id}
    defaults: { _controller: ClabApiOldBundle:RestCart:emptyCart, _format: json }
    methods: [POST]

api_0_cart_add_coupon:
    path:  /cart/{idCart}/coupon/add/{id}
    defaults: { _controller: ClabApiOldBundle:RestCart:addCoupon, _format: json }
    methods: [POST]

api_0_cart_remove_coupon:
    path:  /cart/{idCart}/coupon/remove
    defaults: { _controller: ClabApiOldBundle:RestCart:removeCoupon, _format: json }
    methods: [POST]

api_0_cart_update_quantity:
    path: /cart/update-quantity/{id}/{hash}/{add}
    defaults: { _controller: ClabApiOldBundle:RestCart:updateQuantity, add: null, _format: json }
    methods: [POST]
