## Categories ##
api_0_rest_product_category_from_restaurant:
    path:  /categories/restaurant/{id}
    defaults: { _controller: ClabApiOldBundle:RestProductCategory:getForRestaurant, _format: json }
    methods: [GET]

api_0_rest_product_category_from_chainstore:
    path:  /categories/chainstore/{id}
    defaults: { _controller: ClabApiOldBundle:RestProductCategory:getForChainStore, _format: json }
    methods: [GET]

api_0_rest_product_category_new_for_restaurant:
    path:  /categories/new/restaurant/{id}
    defaults: { _controller: ClabApiOldBundle:RestProductCategory:newForRestaurant, _format: json }
    methods: [POST]

api_0_rest_product_category_new_for_chainstore:
    path:  /categories/new/chainstore/{id}
    defaults: { _controller: ClabApiOldBundle:RestProductCategory:newForChainStore, _format: json }
    methods: [POST]

api_0_rest_product_category_edit:
    path:  /categories/{id}/restaurant/{idRestaurant}
    defaults: { _controller: ClabApiOldBundle:RestProductCategory:edit, _format: json }
    methods: [PUT,PATCH]

api_0_rest_product_category_products:
    path:  /categories/remove/{id}
    defaults: { _controller: ClabApiOldBundle:RestProductCategory:delete, _format: json }
    methods: [POST]


api_0_rest_product_option_edit_choices:
    path:  /option/edit/choices
    defaults: { _controller: ClabApiOldBundle:RestProduct:editOptionChoice, _format: json }
    methods: [POST]


api_0_rest_tax:
    path:  /taxes
    defaults: { _controller: ClabApiOldBundle:RestProduct:taxes, _format: json }
    methods: [GET]

## Products ##
api_0_rest_product_list:
    path:  /products
    defaults: { _controller: ClabApiOldBundle:RestProduct:list, _format: json }
    methods: [GET]
api_0_rest_product_new:
    path:  /products
    defaults: { _controller: ClabApiOldBundle:RestProduct:new, _format: json }
    methods: [POST]

api_0_rest_product_from_restaurant:
    path:  /products/restaurant/{id}
    defaults: { _controller: ClabApiOldBundle:restProduct:getForRestaurant, _format: json }
    methods: [GET]

api_0_rest_product_edit:
    path:  /products/{id}/restaurant/{idRestaurant}
    defaults: { _controller: ClabApiOldBundle:RestProduct:edit, _format: json }
    methods: [PUT,PATCH]

api_0_rest_product_post_edit:
    path:  /products/{id}
    defaults: { _controller: ClabApiOldBundle:RestProduct:editPost, _format: json }
    methods: [POST]

api_0_rest_product_delete:
    path:  /products/{id}
    defaults: { _controller: ClabApiOldBundle:RestProduct:delete, _format: json }
    methods: [DELETE]

api_0_rest_product_reset_stock:
    path:  /catalog/resetstock
    defaults: { _controller: ClabApiOldBundle:RestProduct:resetStock, _format: json }
    methods: [POST]

## Meals ##

api_0_rest_meal_get_restaurant:
    path:  /meals/resto/{id}
    defaults: { _controller: ClabApiOldBundle:RestMeal:getAvailableforRestaurant, _format: json }
    methods: [GET]

api_0_rest_meal_get_menu:
    path:  /meals/restaurant/{id}
    defaults: { _controller: ClabApiOldBundle:RestMeal:getAvailableforRestaurantMenu, _format: json }
    methods: [GET]

api_0_rest_meal_remove:
    path:  /meals/remove/{idMeal}
    defaults: { _controller: ClabApiOldBundle:RestMeal:remove, _format: json }
    methods: [POST]
api_0_rest_meal_remove_menu:
    path:  /meals/remove/menu/{idMeal}/{idRestaurant}
    defaults: { _controller: ClabApiOldBundle:RestMeal:removeForRestaurantMenu, _format: json }
    methods: [POST]
## Options ##
api_0_rest_option_list:
    path:  /options/restaurant/{id}
    defaults: { _controller: ClabApiOldBundle:RestOption:list, _format: json }
    methods: [GET]

api_0_rest_option_product_list:
    path:  /options/product/{id}
    defaults: { _controller: ClabApiOldBundle:RestOption:listForProduct, _format: json }
    methods: [GET]

api_0_rest_option_create_for_restaurant:
    path:  /options/create/{id}
    defaults: { _controller: ClabApiOldBundle:RestOption:create, _format: json }
    methods: [POST]

api_0_rest_option_remove:
    path:  /options/remove/{id}
    defaults: { _controller: ClabApiOldBundle:RestOption:remove, _format: json }
    methods: [POST]

api_0_rest_option_create_choice:
    path:  /options/create/choice/{idProduct}/{value}/{price}
    defaults: { _controller: ClabApiOldBundle:RestOption:createChoice, _format: json }
    methods: [POST]

api_0_rest_option_remove_choice:
    path:  /options/remove/choice/{idChoice}
    defaults: { _controller: ClabApiOldBundle:RestOption:removeChoice, _format: json }
    methods: [POST]

api_0_rest_option_edit_choice:
    path:  /options/edit/choice/{id}
    defaults: { _controller: ClabApiOldBundle:RestOption:patchChoice, _format: json }
    methods: [PUT,PATCH]
