api_0_rest_coupon_list:
    path:  /coupons/{restaurantId}
    defaults: { _controller: ClabApiOldBundle:RestCoupon:list, _format: json }
    methods: [GET]

api_0_rest_coupon_new:
    path:  /coupon/new/{restaurantId}
    defaults: { _controller: ClabApiOldBundle:RestCoupon:new, _format: json }
    methods: [POST]

api_0_rest_product_edit:
    path:  /coupon/edit/{id}
    defaults: { _controller: ClabApiOldBundle:RestCoupon:edit, _format: json }
    methods: [PUT,PATCH]
