api_0_rest_get_log:
    path:  /get/{id}
    defaults: { _controller: ClabApiOldBundle:RestLog:getLog, _format: json }
    methods: [GET]

api_0_rest_new_log:
    path:  /new
    defaults: { _controller: ClabApiOldBundle:RestLog:new, _format: json }
    methods: [POST]

api_0_rest_new_session:
    path:  /session/new
    defaults: { _controller: ClabApiOldBundle:RestLog:newSession, _format: json }
    methods: [POST]
