api_0_rest_restaurant_list_carte:
    path:  /restaurant/list/menu/{slug}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:listMenu, _format: json }
    methods: [GET]
api_0_rest_restaurant_list_categories:
    path:  /restaurant/list/categories/{slug}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:listCategories, _format: json }
    methods: [GET]
api_0_rest_restaurant_list_products:
    path:  /restaurant/list/products
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:listProducts, _format: json }
    methods: [GET]
api_0_rest_restaurant_lis_meals:
    path:  /restaurant/list/meals
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:listMeals, _format: json }
    methods: [GET]

api_0_rest_restaurant_list:
    path:  /restaurant/list/{slug}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:list, _format: json }
    methods: [GET]

api_0_rest_restaurant_quicklist:
    path:  /restaurant/quicklist/
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:quickList, _format: json }
    methods: [GET]

api_0_rest_restaurant_take_away:
    path:  /restaurant/search/takeaway/{latitude}/{longitude}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:searchTakeaway, _format: json }
    methods: [GET]

api_0_rest_restaurant_delivery:
    path:  /restaurant/search/delivery/{latitude}/{longitude}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:searchDelivery, _format: json }
    methods: [GET]

api_0_rest_restaurant_nearby:
    path:  /restaurant/search/nearby/{latitude}/{longitude}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:clickeatSearch, _format: json }
    methods: [GET]

api_0_rest_restaurant_add_favorite:
    path:  /restaurant/add/{user}/{restaurant}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:addFavorite, _format: json }
    methods: [POST]

api_0_rest_restaurant_remove_favorite:
    path:  /restaurant/remove/{user}/{restaurant}
    defaults: { _controller: ClabApiOldBundle:RestRestaurant:removeFavorite, _format: json }
    methods: [POST]
