parameters:
    clab_board.catalog_manager.class: Clab\BoardBundle\Service\CatalogManager
    clab_board.restaurant_manager.class: Clab\BoardBundle\Service\RestaurantManager
    clab_board.dashboard_manager.class: Clab\BoardBundle\Service\DashboardManager
    clab_board.mail_manager.class: Clab\BoardBundle\Service\MailManager
    clab_board.facebook_manager.class: Clab\BoardBundle\Service\FacebookManager
    clab_board.form.flow.event.class: Clab\BoardBundle\Form\Flow\Foodtruck\CreateEventFlow
    clab_board.form.flow.post.class: Clab\BoardBundle\Form\Flow\Social\SocialPostFlow
    clab_board.mixpanel.class: Clab\BoardBundle\Service\Mixpanel

services:
    clab_board.catalog_manager:
        class: %clab_board.catalog_manager.class%
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@router" ]

    clab_board.restaurant_manager:
        class: %clab_board.restaurant_manager.class%
        arguments: [ @libphonenumber.phone_number_util, @doctrine.orm.entity_manager]

    clab_board.dashboard_manager:
        class: %clab_board.dashboard_manager.class%
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@router" ]

    clab_board.mail_manager:
        class: %clab_board.mail_manager.class%
        arguments: [ "@doctrine.orm.entity_manager", "@service_container", "@mailer", "@templating" ]

    clab_board.facebook_manager:
        class: %clab_board.facebook_manager.class%
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@router" ]

    clab.pos_printer_manager:
        class: Clab\BoardBundle\Service\POSPrinterManager
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@router" ]

    app_admin.context_manager:
        class: Clab\BoardBundle\Service\ContextManager
        arguments: [ "@service_container", "@doctrine.orm.entity_manager" ]
        scope: request

    app_admin.billing_manager:
        class: Clab\BoardBundle\Service\BillingManager
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@router" ]

    app_admin.import_manager:
        class: Clab\BoardBundle\Service\ImportManager
        arguments: [ "@service_container", "@doctrine.orm.entity_manager" ]

    app_admin.subscription_manager:
        class: Clab\BoardBundle\Service\SubscriptionManager
        arguments: [ "@service_container", "@doctrine.orm.entity_manager" ]

    app_admin.chain_manager:
        class: Clab\BoardBundle\Service\ChainManager
        arguments: [ "@service_container", "@doctrine.orm.entity_manager" ]

    clab_board.subscription_listener:
        class: Clab\BoardBundle\Service\SubscriptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    board.helper:
        class: Clab\BoardBundle\Controller\Helper
        arguments: [ "@service_container" ]

    clab_board.additional_sale_manager:
        class: Clab\BoardBundle\Service\AdditionalSaleManager
        arguments: [ @doctrine.orm.entity_manager, @form.factory, @translator ]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }