services:
    api.session_manager:
        class: Clab\ApiBundle\Manager\SessionManager
        arguments: [ @doctrine.orm.entity_manager, @request ]
        scope: request

    api.rest_manager:
        class: Clab\ApiBundle\Manager\RestManager
        arguments: [ @service_container, @doctrine.orm.entity_manager, @api.session_manager,@jms_serializer,@request,@form.factory ]
        scope: request

    api.push_manager:
        class: Clab\ApiBundle\Manager\PushManager
        arguments: [ @doctrine.orm.entity_manager,@service_container ]

    api.mixpanel:
        class: Clab\ApiBundle\Manager\Mixpanel
        arguments: [ @doctrine.orm.entity_manager, @router,%mixpanel_token_clickeat% ]

    api_key_user_provider:
        class: Clab\ApiBundle\Security\ApiKeyUserProvider

    api_authentication_failure_handler:
        class: Clab\ApiBundle\Security\AuthenticationFailureHandler
        arguments: ["@event_dispatcher"]

#    api.listener.bridge:
#        class: Clab\ApiBundle\Listener\BridgeListener
#        arguments: ["@session", "@doctrine.orm.entity_manager", "@security.token_storage"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    api_price_formatter:
        class: Clab\ApiBundle\Service\SerializerEvent
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    api.manager.licence:
        class: Clab\ApiBundle\Manager\LicenceManager
        arguments: ["@doctrine.orm.entity_manager"]